(()=>{'use strict';
const c=document.getElementById('game'),g=c.getContext('2d'),W=c.width,H=c.height;
const cash=document.getElementById('cash'),profit=document.getElementById('profit'),served=document.getElementById('served'),rep=document.getElementById('rep'),stock=document.getElementById('stock'),day=document.getElementById('day'),openBtn=document.getElementById('openBtn'),hireBtn=document.getElementById('hireBtn'),expandBtn=document.getElementById('expandBtn'),status=document.getElementById('status'),buildPanel=document.getElementById('buildPanel'),buildBtn=document.getElementById('buildBtn'),buildStatus=document.getElementById('buildStatus'),deliveryBtn=document.getElementById('deliveryBtn'),endBtn=document.getElementById('endBtn'),interactBtn=document.getElementById('interact');
const base={cash:500,profit:0,served:0,rep:50,day:1,open:false,cashier:false,delivery:24,carrying:0,shelves:[8,8,8,8],xp:0,cleanliness:100,expanded:false,fixtures:[]};
let state={...base};try{let s=JSON.parse(localStorage.getItem('cse-v6'));if(s)state={...state,...s}}catch(e){}
const player={x:120,y:610,r:13,speed:4.2,dir:0};let customers=[],keys={},spawn=0,queue=[],particles=[],spill=null,build=false,selected=null,rotation=0,time=8*60;
const shelves=[{x:310,y:205,w:180,h:58,n:'SODA',p:2.49,kind:'cooler'},{x:610,y:205,w:180,h:58,n:'CHIPS',p:1.99},{x:310,y:390,w:180,h:58,n:'CANDY',p:1.69},{x:610,y:390,w:180,h:58,n:'WATER',p:1.79,kind:'cooler'}];
const checkout={x:915,y:465,w:220,h:118},stockroom={x:28,y:105,w:185,h:150};
const catalog={shelf:{name:'Shelf',cost:75,w:105,h:45},fridge:{name:'Refrigerator',cost:150,w:72,h:105},coffee:{name:'Coffee Station',cost:225,w:76,h:76},hotfood:{name:'Hot Food',cost:300,w:105,h:75},trash:{name:'Trash Can',cost:60,w:48,h:48}};
const colors=['#305f86','#9b4d52','#507c59','#8a5b9d','#b56f38','#536a78','#a94d71'];
const money=n=>(n<0?'-$':'$')+Math.abs(n).toFixed(2),save=()=>localStorage.setItem('cse-v6',JSON.stringify(state)),toast=t=>document.getElementById('toast').textContent=t,level=()=>1+Math.floor(state.xp/250),cap=()=>state.expanded?14:10;
function clock(){let h=Math.floor(time/60)%24,m=Math.floor(time%60),ap=h>=12?'PM':'AM',hh=h%12||12;return hh+':'+String(m).padStart(2,'0')+' '+ap}
function ui(){cash.textContent=money(state.cash);profit.textContent='💰 '+money(state.profit)+' profit';served.textContent='👥 '+state.served+' served';rep.textContent='⭐ '+state.rep+' rating';stock.textContent='📦 '+(state.delivery+state.shelves.reduce((a,b)=>a+b,0))+' stock';day.textContent='Day '+state.day+' • '+clock()+' • Level '+level()+' • XP '+state.xp%250+'/250';openBtn.textContent=state.open?'⏸ CLOSE STORE':'▶ OPEN STORE';hireBtn.textContent=state.cashier?'✅ CASHIER HIRED':'👩‍💼 HIRE CASHIER $200';expandBtn.textContent=state.expanded?'✅ STORE EXPANDED':'🏗️ EXPAND $600';status.innerHTML=`Store: <b>${state.open?'OPEN':'CLOSED'}</b> • Carrying <b>${state.carrying}/6</b> • Stockroom <b>${state.delivery}</b> • Clean <b>${state.cleanliness}%</b> • Equipment <b>${state.fixtures.length}</b><br>Soda ${state.shelves[0]}/${cap()} • Chips ${state.shelves[1]}/${cap()} • Candy ${state.shelves[2]}/${cap()} • Water ${state.shelves[3]}/${cap()}`;save()}
function obstacles(){return [...shelves,checkout,stockroom,...state.fixtures]}function near(a,b,d=90){return Math.hypot(a.x-(b.x+b.w/2),a.y-(b.y+b.h/2))<d}function blocked(nx,ny){return obstacles().some(r=>nx>r.x-17&&nx<r.x+r.w+17&&ny>r.y-17&&ny<r.y+r.h+17)}
function interact(){if(build)return toast('Exit Build Mode first.');if(spill&&Math.hypot(player.x-spill.x,player.y-spill.y)<70){spill=null;state.cleanliness=Math.min(100,state.cleanliness+20);state.xp+=5;toast('Floor cleaned +5 XP');ui();return}if(near(player,stockroom,120)){let n=Math.min(6-state.carrying,state.delivery);state.carrying+=n;state.delivery-=n;toast(n?'Picked up '+n+' cases.':'Stockroom empty.');ui();return}for(let i=0;i<4;i++)if(near(player,shelves[i],100)){let n=Math.min(cap()-state.shelves[i],state.carrying);state.shelves[i]+=n;state.carrying-=n;toast(n?'Restocked '+shelves[i].n+' +'+n:'Nothing to stock.');ui();return}if(near(player,checkout,135)&&queue.length&&!state.cashier){checkoutOne();return}toast('Move closer to an interactive area.')}
function addCustomer(){let t=Math.floor(Math.random()*4);customers.push({x:1160,y:650,stage:0,target:t,s:1.05+Math.random()*.55,pat:1300,skin:['#f1c7a5','#c58d68','#8d5f46','#e1aa82'][Math.floor(Math.random()*4)],shirt:colors[Math.floor(Math.random()*colors.length)],hair:['#251c18','#5b3a22','#1d1d1d','#8b633f'][Math.floor(Math.random()*4)],bag:false,phase:Math.random()*6})}
function moveTo(o,tx,ty,s){let dx=tx-o.x,dy=ty-o.y,d=Math.hypot(dx,dy);if(d<s){o.x=tx;o.y=ty;return true}let nx=o.x+dx/d*s,ny=o.y+dy/d*s;if(!obstacles().some(r=>nx>r.x-12&&nx<r.x+r.w+12&&ny>r.y-12&&ny<r.y+r.h+12)){o.x=nx;o.y=ny}else{o.x+=Math.sign(dx)*s*.25;o.y+=Math.sign(dy)*s*.7}return false}
function bonus(){return state.fixtures.reduce((b,f)=>b+(f.type==='coffee'?.35:f.type==='hotfood'?.55:f.type==='fridge'?.15:0),0)}function checkoutOne(){let q=queue.shift();if(!q)return;let p=shelves[q.target].p+bonus();state.cash+=p;state.profit+=p;state.served++;state.xp+=3;state.rep=Math.min(100,state.rep+1);q.stage=4;particles.push({x:1010,y:450,t:55,text:'+'+money(p)});toast('Sale: '+shelves[q.target].n+' '+money(p));ui()}
function update(){if(!build){let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(dx||dy){player.dir=Math.atan2(dy,dx);let l=Math.hypot(dx,dy),nx=player.x+dx/l*player.speed,ny=player.y+dy/l*player.speed;if(!blocked(nx,player.y))player.x=Math.max(20,Math.min(W-20,nx));if(!blocked(player.x,ny))player.y=Math.max(65,Math.min(H-20,ny))}}
if(state.open){time+=.018;if(++spawn>130){spawn=0;if(customers.length<(state.expanded?18:12))addCustomer();if(!spill&&Math.random()<.045){spill={x:440+Math.random()*330,y:300+Math.random()*250};state.cleanliness=Math.max(40,state.cleanliness-15);toast('⚠️ Spill reported — clean it with E.');ui()}}}
for(let o of customers){let sh=shelves[o.target];if(o.stage===0&&moveTo(o,sh.x+sh.w/2,sh.y+sh.h+38,o.s)){if(state.shelves[o.target]>0){state.shelves[o.target]--;o.bag=true;o.stage=1}else{o.stage=3;state.rep=Math.max(0,state.rep-2);ui()}}else if(o.stage===1&&moveTo(o,930,625,o.s)){o.stage=2;queue.push(o)}else if(o.stage===2){let qi=queue.indexOf(o);o.x=940-qi*42;o.y=625;if(qi===0){o.pat--;if(state.cashier&&Math.random()<.045)checkoutOne();else if(o.pat<0){queue.shift();o.stage=3;state.rep=Math.max(0,state.rep-2);ui()}}}else if((o.stage===3||o.stage===4)&&moveTo(o,1170,660,o.s+.3))o.dead=true;o.phase+=.08}customers=customers.filter(o=>!o.dead);particles.forEach(p=>{p.y-=.55;p.t--});particles=particles.filter(p=>p.t>0)}
function rr(x,y,w,h,r,fill,stroke){g.beginPath();if(g.roundRect){g.roundRect(x,y,w,h,r)}else{g.rect(x,y,w,h)};if(fill){g.fillStyle=fill;g.fill()}if(stroke){g.strokeStyle=stroke;g.stroke()}}function txt(t,x,y,s=16,col='#182334',align='center',weight=700){g.fillStyle=col;g.font=`${weight} ${s}px system-ui`;g.textAlign=align;g.fillText(t,x,y)}
function person(o,isPlayer=false){let bob=Math.sin(o.phase||0)*1.2,x=o.x,y=o.y+bob;g.save();g.translate(x,y);g.fillStyle='#0002';g.beginPath();g.ellipse(0,24,13,5,0,0,7);g.fill();g.fillStyle=o.skin||'#e7b58d';g.beginPath();g.arc(0,-16,9,0,7);g.fill();g.fillStyle=o.hair||'#2b211c';g.beginPath();g.arc(0,-19,9,Math.PI,Math.PI*2);g.fill();g.fillStyle=o.shirt||'#246a9b';rr(-9,-7,18,24,4,g.fillStyle);g.fillStyle='#25313c';g.fillRect(-8,17,6,14);g.fillRect(2,17,6,14);g.fillStyle='#ddd';g.fillRect(-9,30,7,3);g.fillRect(2,30,7,3);if(o.bag){g.fillStyle='#39a867';rr(10,3,13,15,2,'#39a867');g.strokeStyle='#174d30';g.strokeRect(12,0,9,6)}g.restore();if(isPlayer)txt('YOU',x,y-34,10,'#10213d')}
function productRows(s,i){let cols=i===0?['#e74c3c','#3498db','#2ecc71']:i===1?['#f5c542','#d35400','#27ae60']:i===2?['#e74c3c','#6c3483','#2980b9']:['#48c9b0','#3498db','#aed6f1'];for(let r=0;r<2;r++)for(let k=0;k<8;k++){g.fillStyle=cols[(k+r)%cols.length];g.fillRect(s.x+12+k*19,s.y+8+r*18,12,14)}}
function fixture(f){let col=f.type==='fridge'?'#c7e7f3':f.type==='coffee'?'#3f332e':f.type==='hotfood'?'#b86d3d':f.type==='trash'?'#888':'#c99a5e';rr(f.x,f.y,f.w,f.h,6,col,'#3336');if(f.type==='fridge'){g.fillStyle='#dff6ff';g.fillRect(f.x+8,f.y+8,f.w-16,f.h-28);g.strokeStyle='#fff';g.strokeRect(f.x+f.w/2,f.y+8,1,f.h-28)}else if(f.type==='coffee'){g.fillStyle='#111';g.fillRect(f.x+10,f.y+10,f.w-20,32);g.fillStyle='#eee';g.fillRect(f.x+18,f.y+48,12,14);g.fillRect(f.x+42,f.y+48,12,14)}else if(f.type==='hotfood'){g.fillStyle='#ffe0a0';g.fillRect(f.x+8,f.y+8,f.w-16,f.h-28);g.fillStyle='#c44';for(let k=0;k<3;k++)g.fillRect(f.x+15+k*28,f.y+20,20,9)}txt(catalog[f.type].name.toUpperCase(),f.x+f.w/2,f.y+f.h-7,9,'#17202a')}
function draw(){g.clearRect(0,0,W,H);let grad=g.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#e7d2a9');grad.addColorStop(1,'#c9a56f');g.fillStyle=grad;g.fillRect(0,0,W,H);for(let y=70;y<H;y+=44)for(let x=0;x<W;x+=44){g.fillStyle=((x+y)/44)%2?'#ffffff10':'#00000008';g.fillRect(x,y,44,44)}
// glass storefront
g.fillStyle='#bde3ee';g.fillRect(0,0,W,72);for(let x=0;x<W;x+=150){g.strokeStyle='#fff8';g.strokeRect(x,0,145,72)}txt('CORNER STORE EMPIRE • OPEN 24/7',W/2,43,23,'#17324d');
rr(stockroom.x,stockroom.y,stockroom.w,stockroom.h,8,'#9dcbe0','#557');txt('STOCKROOM',120,137,18);txt(state.delivery+' cases',120,172,15);txt('Press E to pick up',120,205,12);
shelves.forEach((s,i)=>{g.fillStyle=i===0||i===3?'#e9f8ff':'#f5e1bd';rr(s.x,s.y,s.w,s.h,5,g.fillStyle,'#755');productRows(s,i);g.fillStyle='#604231';g.fillRect(s.x,s.y+s.h-9,s.w,9);txt(s.n+'  '+state.shelves[i]+'/'+cap(),s.x+s.w/2,s.y+s.h+20,13,'#182334')});state.fixtures.forEach(fixture);
rr(checkout.x,checkout.y,checkout.w,checkout.h,6,'#704b38','#4c3025');g.fillStyle='#222';g.fillRect(checkout.x+15,checkout.y+14,64,45);g.fillStyle='#67d5ff';g.fillRect(checkout.x+20,checkout.y+19,54,29);txt(state.cashier?'CASHIER':'REGISTER',checkout.x+145,checkout.y+38,15,'white');txt('CHECKOUT',checkout.x+145,checkout.y+65,12,'#ffe8cf');if(state.cashier)person({x:checkout.x+62,y:checkout.y+90,skin:'#c98f6b',shirt:'#2f7d4a',hair:'#171717',phase:0});
rr(1090,620,100,82,4,'#bfe8f7','#78a');txt('EXIT',1140,665,14);
if(spill){g.fillStyle='#52a9d8aa';g.beginPath();g.ellipse(spill.x,spill.y,31,13,0,0,7);g.fill();txt('⚠ CLEAN',spill.x,spill.y-20,11)}customers.forEach(o=>person(o));person({...player,skin:'#d7a57d',shirt:'#245d88',hair:'#33241e',phase:performance.now()/180},true);if(state.carrying)txt('📦 '+state.carrying,player.x+27,player.y-15,13);particles.forEach(p=>txt(p.text,p.x,p.y,14,'#087a36'));if(build){g.fillStyle='#10213ddd';g.fillRect(0,72,W,40);txt(selected?'BUILD: '+catalog[selected].name+' • click floor • R rotate':'BUILD MODE • choose equipment below',W/2,99,16,'white')}requestAnimationFrame(loop)}
function loop(){update();draw()}
function toggleBuild(){if(state.open)return toast('Close the store before building.');build=!build;selected=null;buildPanel.classList.toggle('on',build);buildPanel.style.display=build?'block':'none';buildBtn.classList.toggle('active',build);buildStatus.textContent=build?'Choose equipment to place.':'Build mode off.';toast(build?'Build Mode ON':'Build Mode OFF')}
function overlaps(r){return obstacles().some(o=>r.x<o.x+o.w+12&&r.x+r.w+12>o.x&&r.y<o.y+o.h+12&&r.y+r.h+12>o.y)}function place(ev){if(!build||!selected)return;let b=c.getBoundingClientRect(),mx=(ev.clientX-b.left)*W/b.width,my=(ev.clientY-b.top)*H/b.height,it=catalog[selected],w=rotation%2?it.h:it.w,h=rotation%2?it.w:it.h,r={x:Math.round(mx-w/2),y:Math.round(my-h/2),w,h,type:selected};if(r.x<10||r.y<120||r.x+r.w>W-10||r.y+r.h>H-10||overlaps(r))return toast('Cannot place there.');if(state.cash<it.cost)return toast('Need '+money(it.cost)+' for '+it.name);state.cash-=it.cost;state.profit-=it.cost;state.fixtures.push(r);state.xp+=10;toast(it.name+' placed.');ui()}
document.addEventListener('keydown',e=>{keys[e.key]=true;if(e.key.toLowerCase()==='e')interact();if(e.key.toLowerCase()==='r'&&build){rotation++;toast('Placement rotated.')}});document.addEventListener('keyup',e=>keys[e.key]=false);document.querySelectorAll('[data-key]').forEach(b=>{let k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();keys[k]=true};b.onpointerup=b.onpointerleave=()=>keys[k]=false});document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>{selected=b.dataset.build;document.querySelectorAll('[data-build]').forEach(q=>q.classList.toggle('selected',q===b));buildStatus.textContent='Selected '+catalog[selected].name+' — click open floor.'});c.onpointerdown=place;interactBtn.onclick=interact;buildBtn.onclick=toggleBuild;openBtn.onclick=()=>{if(build)return toast('Exit Build Mode first.');state.open=!state.open;toast(state.open?'Store OPEN — customers are arriving.':'Store closed to new customers.');ui()};hireBtn.onclick=()=>{if(state.cashier)return toast('Cashier already hired.');if(state.cash<200)return toast('Need $200.');state.cash-=200;state.profit-=200;state.cashier=true;ui();toast('Cashier hired.')};deliveryBtn.onclick=()=>{if(state.cash<40)return toast('Not enough cash.');state.cash-=40;state.profit-=40;state.delivery+=20;ui();toast('Delivery arrived: +20 cases.')};expandBtn.onclick=()=>{if(state.expanded)return toast('Already expanded.');if(state.cash<600)return toast('Need $600.');state.cash-=600;state.profit-=600;state.expanded=true;state.xp+=50;ui();toast('Store expanded!')};endBtn.onclick=()=>{if(state.open)return toast('Close the store first.');if(build)return toast('Exit Build Mode first.');let cost=state.cashier?35:15;state.cash-=cost;state.profit-=cost;state.day++;time=8*60;state.cleanliness=Math.min(100,state.cleanliness+10);ui();toast('Day ended. Expenses '+money(cost))};buildPanel.style.display='none';ui();loop();})();
