(()=>{'use strict';
const c=document.getElementById('game'),x=c.getContext('2d'); const W=c.width,H=c.height;
let state={cash:500,profit:0,served:0,rep:50,day:1,open:false,cashier:false,delivery:12,carrying:0,shelves:[6,6,6,6]};
try{let s=JSON.parse(localStorage.getItem('cse-v3'));if(s)state={...state,...s}}catch(e){}
const player={x:100,y:500,r:15,speed:3.8}; let customers=[],keys={},spawn=0,queue=[];
const shelves=[{x:260,y:135,w:170,h:65,n:'SODA',p:2.49},{x:530,y:135,w:170,h:65,n:'CHIPS',p:1.99},{x:260,y:315,w:170,h:65,n:'CANDY',p:1.69},{x:530,y:315,w:170,h:65,n:'WATER',p:1.79}];
const checkout={x:745,y:430,w:175,h:90}, stockroom={x:25,y:80,w:145,h:120};
function save(){localStorage.setItem('cse-v3',JSON.stringify(state))} function money(n){return '$'+n.toFixed(2)}
function toast(t){document.getElementById('toast').textContent=t}
function ui(){document.getElementById('cash').textContent=money(state.cash);document.getElementById('profit').textContent='💰 '+money(state.profit)+' profit';document.getElementById('served').textContent='👥 '+state.served+' served';document.getElementById('rep').textContent='⭐ '+state.rep;document.getElementById('stock').textContent='📦 '+(state.delivery+state.shelves.reduce((a,b)=>a+b,0))+' stock';document.getElementById('day').textContent='Day '+state.day+' • Level '+Math.min(5,1+Math.floor(state.served/30));document.getElementById('openBtn').textContent=state.open?'⏸ CLOSE STORE':'▶ OPEN STORE';document.getElementById('hireBtn').textContent=state.cashier?'✅ CASHIER HIRED':'👩‍💼 HIRE CASHIER $200';document.getElementById('status').innerHTML=`Store: <b>${state.open?'OPEN':'CLOSED'}</b> • Carrying: <b>${state.carrying}/6</b> • Stockroom: <b>${state.delivery}</b> • Cashier: <b>${state.cashier?'Yes':'No'}</b><br>Shelves: Soda ${state.shelves[0]}/10 • Chips ${state.shelves[1]}/10 • Candy ${state.shelves[2]}/10 • Water ${state.shelves[3]}/10`;save()}
function near(a,b,d=70){return Math.hypot(a.x-(b.x+b.w/2),a.y-(b.y+b.h/2))<d}
function interact(){if(near(player,stockroom,100)){let take=Math.min(6-state.carrying,state.delivery);state.carrying+=take;state.delivery-=take;toast(take?'Picked up '+take+' items. Take them to a shelf.':'No stock available. Order a delivery.');ui();return}for(let i=0;i<shelves.length;i++){if(near(player,shelves[i],90)){let add=Math.min(10-state.shelves[i],state.carrying);state.shelves[i]+=add;state.carrying-=add;toast(add?'Restocked '+shelves[i].n+' with '+add+' items.':shelves[i].n+' is full or you are not carrying stock.');ui();return}}if(near(player,checkout,110)&&queue.length&&!state.cashier){checkoutOne();return}toast('Nothing to interact with here.')}
function addCustomer(){let idx=Math.floor(Math.random()*4);customers.push({x:900,y:565,r:13,stage:0,target:idx,buy:false,id:Math.random()})}
function moveTo(o,tx,ty,s=1.7){let dx=tx-o.x,dy=ty-o.y,d=Math.hypot(dx,dy);if(d<s){o.x=tx;o.y=ty;return true}o.x+=dx/d*s;o.y+=dy/d*s;return false}
function checkoutOne(){let q=queue.shift();if(!q)return;let p=shelves[q.target].p;state.cash+=p;state.profit+=p;state.served++;state.rep=Math.min(100,state.rep+1);q.stage=4;toast('Sale! '+shelves[q.target].n+' '+money(p));ui()}
function update(){let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(dx||dy){let l=Math.hypot(dx,dy);player.x=Math.max(18,Math.min(W-18,player.x+dx/l*player.speed));player.y=Math.max(18,Math.min(H-18,player.y+dy/l*player.speed))}
if(state.open&&++spawn>150){spawn=0;if(customers.length<8)addCustomer()}
for(let o of customers){let sh=shelves[o.target];if(o.stage===0&&moveTo(o,sh.x+sh.w/2,sh.y+sh.h+35)){if(state.shelves[o.target]>0){state.shelves[o.target]--;o.buy=true;o.stage=1}else{o.stage=3;state.rep=Math.max(0,state.rep-1);ui()}}else if(o.stage===1&&moveTo(o,760,535)){o.stage=2;queue.push(o)}else if(o.stage===2){let qi=queue.indexOf(o);o.x=780-qi*32;o.y=520;if(state.cashier&&qi===0&&Math.random()<.025)checkoutOne()}else if(o.stage===3&&moveTo(o,930,570))o.dead=true;else if(o.stage===4&&moveTo(o,930,570))o.dead=true}customers=customers.filter(o=>!o.dead)}
function rect(r,color){x.fillStyle=color;x.fillRect(r.x,r.y,r.w,r.h)} function label(t,px,py,size=18){x.fillStyle='#17202a';x.font=`bold ${size}px system-ui`;x.textAlign='center';x.fillText(t,px,py)}
function draw(){x.clearRect(0,0,W,H);x.fillStyle='#d7b77e';x.fillRect(0,0,W,H);for(let yy=0;yy<H;yy+=40)for(let xx=0;xx<W;xx+=40){x.fillStyle=((xx+yy)/40)%2?'#ddc18d':'#e5c998';x.fillRect(xx,yy,40,40)}
rect(stockroom,'#b8d8ef');label('📦 STOCKROOM',97,115,16);label(state.delivery+' items',97,145,15);label('Press E',97,174,13);
shelves.forEach((s,i)=>{rect(s,'#fff5d9');x.fillStyle='#805844';x.fillRect(s.x,s.y+s.h-9,s.w,9);label(['🥤','🍟','🍫','💧'][i],s.x+s.w/2,s.y+28,25);label(s.n+'  '+state.shelves[i]+'/10',s.x+s.w/2,s.y+53,14)});
rect(checkout,'#835947');label(state.cashier?'👩‍💼 CASHIER':'🧑 YOU',checkout.x+checkout.w/2,checkout.y+35,18);label('CHECKOUT',checkout.x+checkout.w/2,checkout.y+67,14);x.fillStyle='#b7e1f7';x.fillRect(865,545,80,50);label('🚪 EXIT',905,575,14);
for(let o of customers){label(o.buy?'🧑🛍️':'🧑',o.x,o.y,24)} label('🧑‍💼',player.x,player.y,27);if(state.carrying)label('📦'+state.carrying,player.x,player.y-25,13);requestAnimationFrame(loop)}
function loop(){update();draw()} document.addEventListener('keydown',e=>{keys[e.key]=true;if(e.key.toLowerCase()==='e')interact()});document.addEventListener('keyup',e=>keys[e.key]=false);
document.querySelectorAll('[data-key]').forEach(b=>{let k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();keys[k]=true});['pointerup','pointerleave','pointercancel'].forEach(ev=>b.addEventListener(ev,()=>keys[k]=false))});document.getElementById('interact').onclick=interact;
document.getElementById('openBtn').onclick=()=>{state.open=!state.open;toast(state.open?'Store OPEN — customers are coming!':'Store closed to new customers.');ui()};document.getElementById('hireBtn').onclick=()=>{if(state.cashier)return toast('You already have a cashier.');if(state.cash<200)return toast('You need $200 to hire a cashier.');state.cash-=200;state.cashier=true;toast('Cashier hired! Checkout is now automatic.');ui()};document.getElementById('deliveryBtn').onclick=()=>{if(state.cash<40)return toast('Not enough cash.');state.cash-=40;state.profit-=40;state.delivery+=20;toast('Delivery arrived: +20 stock.');ui()};document.getElementById('endBtn').onclick=()=>{if(state.open)return toast('Close the store before ending the day.');let cost=state.cashier?35:15;state.cash-=cost;state.profit-=cost;state.day++;toast('Day ended. Expenses: '+money(cost));ui()};ui();loop();
})();
